extends:
  - react-app
plugins:
  - react
  - jsx-a11y
  - import
globals:
  window: true
  document: true
rules:
  react/jsx-filename-extension: off
  react/jsx-space-before-closing: off
  react/prefer-stateless-function: warn
  react/prop-types: off
  jsx-a11y/img-has-alt: off
  jsx-a11y/href-no-hash: off  
  import/no-extraneous-dependencies: off
  indent: [2, 4]
  react/jsx-indent: [2, 4]
  react/jsx-indent-props: [2, 4]
